### ISSUE TITLE
Hibernate support

### ISSUE THREAD

**Issue by Amitesh** [seqizz/ulauncher-session-actions#3]
Hi @seqizz ,

Any plan to support fot "Hibernate" for Ubuntu?

Thanks for Awesome work. :)

-Amitesh

**Comment by seqizz** [comment]
Hi there,

Unfortunately I am not using ulauncher anymore. But it's always nice to give something useful :)

[Latest commit](https://github.com/seqizz/ulauncher-session-actions/commit/8696f0abed7f793d7d6240b38d4d239387182905) should add the hibernate support. Could you update your plugin and ping if it has issues? I just set the systemctl hibernate command as default.

**Comment by Amitesh** [comment]
Thanks @seqizz

I tried to add your extention using [https://github.com/seqizz/ulauncher-session-actions](https://github.com/seqizz/ulauncher-session-actions) but unfortunetly it is not getting added.
I am using Ulauncher 5.6.1 which support Extention API 2.0.0.

Actually, I was using [https://github.com/leinardi/ulauncher-exit-gnome](https://github.com/leinardi/ulauncher-exit-gnome) plugin and from there I came to you extension git. Bot ext dosn't have the support thats why I have made the request.

**Comment by seqizz** [comment]
Well, like I said I am not using it anymore. Last time it was possible to use old API. There is another issue about it, which didn't lead to somewhere apparently.

You might want to check out forks, in a quick glance I see https://github.com/insanengineer/ulauncher-session-actions has a commit mentioning 2.0.0. :crossed_fingers:
